syntax = "proto3";

package application.dict;

option php_namespace = "Modules\\ApiProto\\Protobuf\\Application\\Dict";
option go_package = "github.com/shandong-ziyou/dailian/proto/application/dict";
option java_multiple_files = true;
option java_package = "com.shandong.ziyou.dailian.proto.application.dict";

import "ApiProto/common.proto";

// 获取单个字典列表
// /api/proto/application/dict/list
message ApplicationDictListRequest {
  string dict_type = 1;  // 字典类型
}

// /api/proto/application/dict/list
message ApplicationDictListResponse {
  ApiProto.Common.BaseResponse base = 1;
  string dict_type = 2;  // 回传过滤条件
  repeated ApplicationDictData data = 3;
}

message ApplicationDictData {
  string label = 1;  // 字典标签
  string value = 2;  // 字典值
  int32 sort = 3;    // 排序
  string extra = 4;  // 扩展数据(JSON格式)
}

// 批量获取字典
// /api/proto/application/dict/batch
message ApplicationDictBatchRequest {
  repeated string dict_types = 1;  // 字典类型列表
}

// /api/proto/application/dict/batch
message ApplicationDictBatchResponse {
  ApiProto.Common.BaseResponse base = 1;
  repeated ApplicationDictTypeData data = 2;
}

message ApplicationDictTypeData {
  string dict_type = 1;  // 字典类型(回传过滤条件)
  repeated ApplicationDictData items = 2;
}