syntax = "proto3";

package application.feature;

option php_namespace = "Modules\\ApiProto\\Protobuf\\Application\\Feature";
option go_package = "github.com/shandong-ziyou/dailian/proto/application/feature";
option java_multiple_files = true;
option java_package = "com.shandong.ziyou.dailian.proto.application.feature";

import "ApiProto/common.proto";

// 获取我的可用功能列表
// /api/proto/application/feature/list
message ApplicationFeatureListRequest {
  // 空 Request,使用 token 中的 user_id
}

// /api/proto/application/feature/list
message ApplicationFeatureListResponse {
  ApiProto.Common.BaseResponse base = 1;
  repeated string features = 2;  // 功能标识列表
}