<?php

namespace Modules\DcatAdmin\DcatAdmin\Grid\Actions;

use Dcat\Admin\Grid\Actions\Edit as BaseEdit;

class Edit extends BaseEdit
{
    public function href()
    {
        return parent::href(); // TODO: Change the autogenerated stub
    }
}
