<?php

// DcatAdmin模块后台菜单配置
// 包含：系统核心菜单 + Admin模块功能菜单
// 菜单ID范围: 1-9 (系统核心) + 10xxx (Admin模块功能)
return [
    // === Dcat Admin 系统核心菜单 (ID: 1-9) ===
    [
        'id' => 1,
        'parent_id' => 0,
        'order' => 1,
        'title' => '首页',
        'icon' => 'feather icon-bar-chart-2',
        'uri' => '/',
    ],
    [
        'id' => 2,
        'parent_id' => 0,
        'order' => 2,
        'title' => '系统管理',
        'icon' => 'feather icon-settings',
        'uri' => '',
    ],
    [
        'id' => 3,
        'parent_id' => 2,
        'order' => 3,
        'title' => '用户',
        'icon' => '',
        'uri' => 'auth/users',
    ],
    [
        'id' => 4,
        'parent_id' => 2,
        'order' => 4,
        'title' => '角色',
        'icon' => '',
        'uri' => 'auth/roles',
    ],
    [
        'id' => 5,
        'parent_id' => 2,
        'order' => 5,
        'title' => '权限',
        'icon' => '',
        'uri' => 'auth/permissions',
    ],
    [
        'id' => 6,
        'parent_id' => 2,
        'order' => 6,
        'title' => '菜单',
        'icon' => '',
        'uri' => 'auth/menu',
    ],
    [
        'id' => 7,
        'parent_id' => 2,
        'order' => 7,
        'title' => '扩展',
        'icon' => '',
        'uri' => 'auth/extensions',
    ],

    // === DcatAdmin 模块功能菜单 (ID: 10xxx) ===
    [
        'id' => 10001,
        'parent_id' => 0,
        'order' => 10001,
        'title' => 'Admin模块',
        'icon' => 'feather icon-settings',
        'uri' => '',
    ],
    [
        'id' => 10002,
        'parent_id' => 10001,
        'order' => 10002,
        'title' => 'Vue仪表盘',
        'icon' => 'feather icon-monitor',
        'uri' => 'module_dcatadmin/vue-dashboard',
    ],
    [
        'id' => 10009,
        'parent_id' => 10001,
        'order' => 10009,
        'title' => 'Element组件演示',
        'icon' => 'feather icon-layers',
        'uri' => 'module_dcatadmin/elements-demo',
    ],
    [
        'id' => 10010,
        'parent_id' => 10001,
        'order' => 10010,
        'title' => '基础组件演示',
        'icon' => 'feather icon-box',
        'uri' => 'module_dcatadmin/basic-demo',
    ],
    [
        'id' => 10011,
        'parent_id' => 10001,
        'order' => 10011,
        'title' => '表单组件演示',
        'icon' => 'feather icon-edit',
        'uri' => 'module_dcatadmin/form-demo',
    ],
    [
        'id' => 10012,
        'parent_id' => 10001,
        'order' => 10012,
        'title' => '数据展示演示',
        'icon' => 'feather icon-grid',
        'uri' => 'module_dcatadmin/data-demo',
    ],
    [
        'id' => 10003,
        'parent_id' => 10001,
        'order' => 10003,
        'title' => '图表演示',
        'icon' => 'feather icon-bar-chart-2',
        'uri' => 'module_dcatadmin/metrics',
    ],
    [
        'id' => 10004,
        'parent_id' => 10001,
        'order' => 10004,
        'title' => '高级图表',
        'icon' => 'feather icon-activity',
        'uri' => 'module_dcatadmin/metrics2',
    ],
    [
        'id' => 10005,
        'parent_id' => 10001,
        'order' => 10005,
        'title' => '路由查看',
        'icon' => 'feather icon-navigation',
        'uri' => 'module_dcatadmin/routers',
    ],
    [
        'id' => 10006,
        'parent_id' => 10001,
        'order' => 10006,
        'title' => '配置查看',
        'icon' => 'feather icon-settings',
        'uri' => 'module_dcatadmin/config',
    ],
    [
        'id' => 10007,
        'parent_id' => 10001,
        'order' => 10007,
        'title' => '菜单同步',
        'icon' => 'feather icon-refresh-cw',
        'uri' => 'module_dcatadmin/menu-sync',
    ],
    [
        'id' => 10008,
        'parent_id' => 10001,
        'order' => 10008,
        'title' => '系统信息',
        'icon' => 'feather icon-server',
        'uri' => 'module_dcatadmin/system-info',
    ],
];
